### ISSUE TITLE
Cada condición de if puede ser un método

### ISSUE THREAD

**Issue by gibran-ds** [Gxboyz4/DominoArquitecturaACM#26]
https://github.com/Gxboyz4/DominoArquitecturaACM/blob/0c5d67c627e4c1a40aef5a30960a5625166d0fc8/ProyectoArquitecturaDominoACM/src/main/java/org/itson/proyectoarquitecturadominoacm/Tablero/TableroModelo.java#L200

if(fichas.size() == 0)
{
    return sextoCaso;
}
if(fichas.getFirst().equals(ficha))
{
    return falso;
}
if(fichas.getLast().equals(ficha))
{
    return falso;
}

// son sugerencias de nombres, quizás encuentren mejores pero la idea es dejar más claro para después y otros desarrolladores
if(tableroVacio()){

}
if(coincideConPrimeraFicha(ficha)){

}
if(coincideConUltimaFicha(ficha)){

}

**Comment by PabolOne** [comment]
Se separo el contenido de los if en métodos tanto del validarColocacionDerecha como de validarColocacionIzquierda
